name: Deploy
on:
   push:
    branches: [master]

jobs:
   deploy:
    name: Deploy Datalake
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Terraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "{{secrets.AWS_ACCESS_KEY_ID}}"
          aws-secret-access-key: "{{secrets.AWS_SECRET_ACCESS_KEY}}"
          aws-region: sa-east-1

      - name: IAC Terraform
        env:
          COMMAND_IAC: Terraform
        run: 
          cd iac
          $COMMAND_IAC init
          $COMMAND_IAC validate
          $COMMAND_IAC plan
          $COMMAND_IAC apply -auto-approve
